name: Deploy to GitHub Pages

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch
  workflow_dispatch:  # Enable manual "Run workflow" button

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/portfolio-app:latest -f Dockerfile .
          docker push ghcr.io/${{ github.repository_owner }}/portfolio-app:latest

      - name: Extract built static files from Docker
        run: |
          docker create --name temp-container ghcr.io/${{ github.repository_owner }}/portfolio-app:latest
          docker cp temp-container:/usr/share/nginx/html ./dist-output
          docker rm temp-container

      - name: Debug dist-output
        run: |
          echo "Dist output files:"
          ls -lR ./dist-output
          echo "Index.html preview:"
          head -n 10 ./dist-output/index.html || echo "index.html not found"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist-output
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}