name: Deploy to GitHub Pages

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch
  workflow_dispatch:  # Enable manual "Run workflow" button

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image from nested Angular app
        run: |
          docker build -t portfolio-app:latest -f Dockerfile .

      - name: Extract built static files from Docker
        run: |
          docker create --name temp-container portfolio-app:latest
          docker cp temp-container:/usr/share/nginx/html ./dist-output
          docker rm temp-container

      - name: Debug dist-output (Optional)
        run: |
          echo "Dist output files:"
          ls -l ./dist-output
          echo "Index.html preview:"
          head -n 10 ./dist-output/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist-output
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}