name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the Docker image from the root (where Dockerfile is)
      - name: Build Docker Image
        run: |
          docker build -t portfolio-app:latest -f Dockerfile .

      # Run the container and extract static files
      - name: Extract Static Files
        run: |
          docker create --name temp-container portfolio-app:latest
          docker cp temp-container:/usr/share/nginx/html ./dist-output
          docker rm temp-container

      # Deploy to GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist-output
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}